# Generated by Django 5.2.17 on 2026-08-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskflow', '0003_techstack_user_tech_stack'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usertechstack',
            new_name='taskflow_us_user_id_c90084_idx',
            old_name='taskflow_uts_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='usertechstack',
            new_name='taskflow_us_tech_st_35c98e_idx',
            old_name='taskflow_uts_tech_id_idx',
        ),
    ]
