# Generated by Django 5.2.17 on 2026-08-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskflow', '0006_tasksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='taskflow.techstack'),
        ),
    ]
