# Generated by Django 5.2.17 on 2026-08-25 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskflow', '0007_task_tech_stack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=20)),
                ('input_format', models.TextField()),
                ('output_format', models.TextField()),
                ('constraints', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('starter_code', models.JSONField(blank=True, default=dict)),
                ('allowed_languages', models.JSONField(blank=True, default=list)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coding_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CodingProblemTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='taskflow.codingproblem')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='codingproblem',
            index=models.Index(fields=['status'], name='taskflow_co_status_0814ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='codingproblemtestcase',
            constraint=models.UniqueConstraint(fields=('problem', 'order'), name='unique_problem_testcase_order'),
        ),
    ]
