# Generated by Django 5.2.17 on 2026-08-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskflow', '0009_codesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='mode',
            field=models.CharField(choices=[('RUN', 'Run (public tests)'), ('SUBMIT', 'Submit (public + hidden tests)')], default='SUBMIT', max_length=10),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='verdict',
            field=models.CharField(blank=True, choices=[('PENDING', 'Queued for execution'), ('RUNNING', 'Running'), ('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('COMPILATION_ERROR', 'Compilation Error'), ('RUNTIME_ERROR', 'Runtime Error'), ('TIME_LIMIT_EXCEEDED', 'Time Limit Exceeded'), ('MEMORY_LIMIT_EXCEEDED', 'Memory Limit Exceeded'), ('SYSTEM_ERROR', 'System Error')], max_length=30, null=True),
        ),
    ]
