# Generated by Django 5.2.17 on 2026-08-26 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskflow', '0010_codesubmission_completed_at_codesubmission_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_assignments', models.BooleanField(default=True, help_text='Notify when a task is assigned to me.')),
                ('submission_reviews', models.BooleanField(default=True, help_text='Notify when my submission is reviewed.')),
                ('task_deadlines', models.BooleanField(default=True, help_text='Notify about task deadlines and overdue tasks.')),
                ('admin_announcements', models.BooleanField(default=True, help_text='Receive general/admin announcements.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'notification preferences',
            },
        ),
    ]
