# Generated by Django 5.2.17 on 2026-08-27 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskflow', '0011_notificationpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('correctness', models.TextField()),
                ('bugs', models.JSONField(blank=True, default=list)),
                ('code_quality', models.TextField()),
                ('time_complexity', models.CharField(blank=True, max_length=200)),
                ('space_complexity', models.CharField(blank=True, max_length=200)),
                ('edge_cases', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='taskflow.codesubmission')),
            ],
        ),
    ]
