# Generated by Django 5.2.17 on 2026-08-28 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskflow', '0013_task_difficulty_and_submission_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending evaluation'), ('COMPLETED', 'Evaluation complete'), ('FAILED', 'Evaluation failed (retry allowed)')], default='PENDING', max_length=20)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('total_score', models.PositiveSmallIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('error_message', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='tasksubmission',
            name='unique_task_submission_user',
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['user', 'task'], name='taskflow_ta_user_id_ee8af6_idx'),
        ),
        migrations.AddField(
            model_name='taskevaluation',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_evaluation', to='taskflow.tasksubmission'),
        ),
        migrations.AddIndex(
            model_name='taskevaluation',
            index=models.Index(fields=['status'], name='taskflow_ta_status_dc28af_idx'),
        ),
    ]
